### ISSUE TITLE
Separator Misspelled

### ISSUE THREAD

**Issue by mudgen** [bcnmy/metatx-standard#14]
The word 'separator' is misspelled in this source code: https://github.com/bcnmy/metatx-standard/blob/master/src/contracts/lib/EIP712Base.sol

**Comment by livingrock7** [comment]
Thanks. 
https://github.com/bcnmy/metatx-standard/commit/3e8e496f245e012b33a4e12634b532b601d0f0f5
Will get merged
closing this issue
