### ISSUE TITLE
Linter error: missing SPDX license identifier

### ISSUE THREAD

**Issue by bbjay** [bcnmy/metatx-standard#9]
I get the following linting error when adding the contracts to my project:

> SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

**Comment by livingrock7** [comment]
@bbjay pushing the license identifiers in contracts. Could you tell me name of any specific contracts you're trying to import?

**Comment by livingrock7** [comment]
@tomarsachin2271 created PR for this kindly check and approve
https://github.com/bcnmy/metatx-standard/pull/11

**Comment by tomarsachin2271** [comment]
Fixed in master branch. So closing this issue.
